
% construct a tree node
function treenode = TreeNode(nodeNo,...
                            chosedFeature,...
                            branch,...
                            splitPosition,...
                            parentNode,...
                            dataSet,...
                            isLeaf,...
                            label)

                       
                        
treenode = struct('nodeNo',nodeNo, ...
                  'chosedFeature',chosedFeature,...
                  'branch',branch,...
                  'splitPosition', splitPosition,...
                  'parentNode',parentNode,...
                  'dataSet', dataSet,...
                  'isLeaf',isLeaf,...
                  'label', label...
                  );